### ISSUE TITLE
Missing bash script

### ISSUE THREAD

**Issue by php4umagento** [aileftech/wikipedia-autovideo#1]
Running simple task and getting error

`Running: sh concat.sh output/list.txt output/final/xxxxxxxx.mp4
sh: 0: Can't open concat.sh
 ERROR!
Exception in thread "main" java.lang.RuntimeException: Error executing sh script
        at com.autovideo.utils.ProcessRunner.run(ProcessRunner.java:32)
        at com.autovideo.video.VideoRenderer.render(VideoRenderer.java:84)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:219)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)
`

**Comment by aileftech** [comment]
Hi, thanks for reporting this. I've added the script to the repo now so let me know if it's working fine :)
