### ISSUE TITLE
Issue with starting

### ISSUE THREAD

**Issue by burakclk1** [aileftech/wikipedia-autovideo#2]
Jul 27, 2022 12:32:20 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "set-cookie: WMF-Last-Access=27-Jul-2022;Path=/;HttpOnly;secure;Expires=Sun, 28 Aug 2022 00:00:00 GMT". Invalid 'expires' attribute: Sun, 28 Aug 2022 00:00:00 GMT
Jul 27, 2022 12:32:20 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "set-cookie: WMF-Last-Access-Global=27-Jul-2022;Path=/;Domain=.wikipedia.org;HttpOnly;secure;Expires=Sun, 28 Aug 2022 00:00:00 GMT". Invalid 'expires' attribute: Sun, 28 Aug 2022 00:00:00 GMT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running: sh output/clean.sh
Exception in thread "main" java.io.IOException: Cannot run program "sh": CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at java.base/java.lang.Runtime.exec(Runtime.java:615)
        at java.base/java.lang.Runtime.exec(Runtime.java:439)
        at java.base/java.lang.Runtime.exec(Runtime.java:322)
        at com.autovideo.utils.ProcessRunner.run(ProcessRunner.java:19)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:181)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)

**Comment by burakclk1** [comment]
I solved the problem with SLF4J. But keep getting this error 
Running: sh output/clean.sh
Exception in thread "main" java.io.IOException: Cannot run program "sh": CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at java.base/java.lang.Runtime.exec(Runtime.java:615)
        at java.base/java.lang.Runtime.exec(Runtime.java:439)
        at java.base/java.lang.Runtime.exec(Runtime.java:322)
        at com.autovideo.utils.ProcessRunner.run(ProcessRunner.java:19)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:181)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 7 more

**Comment by frankelia** [comment]
It seems like you are missing the `clean.sh` script that's in the `output` directory. Can you confirm it's there?

**Comment by burakclk1** [comment]
yea it's there

**Comment by burakclk1** [comment]
Solved this problem 
Added PATH in Windows C:\Program Files\git\bin
