### ISSUE TITLE
Error on SVG to JPG

### ISSUE THREAD

**Issue by burakclk1** [aileftech/wikipedia-autovideo#4]
Running: sh output/clean.sh
 OK!
Converting flag SVG to JPG...
Running: convert tmp/overlay.svg tmp/overlay.jpg
Invalid Parameter - /overlay.svg
 ERROR!
Exception in thread "main" java.lang.RuntimeException: Error executing sh script
        at com.autovideo.utils.ProcessRunner.run(ProcessRunner.java:32)
        at com.autovideo.img.ImgUtils.convert(ImgUtils.java:31)
        at com.autovideo.wiki.WikiVideoCreator.createVideo(WikiVideoCreator.java:199)
        at com.autovideo.wiki.WikiVideoCreator.main(WikiVideoCreator.java:261)

**Comment by aileftech** [comment]
Hi, from your previous issue it seems you are running on Windows. 

The `convert` command is part of the `imagemagick` tool. You have to install that (if it's available on Windows) or find another way to perform the conversion.
